###
POST http://127.0.0.1:8889/api/code/new
Content-Type: application/json
Cache-Control: no-cache

{ "code": "package platform;\n\npublic class CodeDTO {\n\n    private String code;\n\n    public String getCode() {\n        return code;\n    }\n\n    public void setCode(String code) {\n        this.code = code;\n    }\n}"}

###
POST http://127.0.0.1:8889/api/code/new
Content-Type: application/json
Cache-Control: no-cache

{ "code": "public class IdDTO {\n    private String id;\n}"}

###
GET http://127.0.0.1:8889/code/1

###
GET http://127.0.0.1:8889/api/code/1

###
GET http://127.0.0.1:8889/code/new

###
GET http://127.0.0.1:8889/code/latest

###
GET http://127.0.0.1:8889/api/code/latest
