###
POST http://127.0.0.1:8889/api/code/new
Content-Type: application/json
Cache-Control: no-cache

{ "code": "Code1", "time": "0", "views":  "0"}

###
POST http://127.0.0.1:8889/api/code/new
Content-Type: application/json
Cache-Control: no-cache

{ "code": "Secret code", "time": "5000", "views":  "5"}

###
GET http://127.0.0.1:8889/api/code/910198cc-fd25-48f3-8df3-5374bd350b8e

###
GET http://127.0.0.1:8889/code/d064fd9f-46bf-45cb-9b19-2ed126a7a0ab

###
GET http://127.0.0.1:8889/code/new

###
GET http://127.0.0.1:8889/code/latest

###
GET http://127.0.0.1:8889/api/code/latest

###
POST http://127.0.0.1:8889/actuator/shutdown
